version: "3.3"
services:
  app:
    build: .
    environment:
      DATABASE_URL: mysql://root:pw@localhost:3306/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
      - "18187:18187"
      - "18189:18189"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - db
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8188:8080

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password=pw -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_DATABASE=db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

